POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "username": "billyTheKid",
    "password": "superSecret"
}

###
GET http://localhost:8080/users/aaa HTTP/1.1
content-type: application/json
 
###
POST http://localhost:8080/logout HTTP/1.1
content-type: application/json

{
    "username": "billyTheKid",
    "password": "superSecret"
}
